[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/gallery"
  to = "/.netlify/functions/gallery"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
